# Site settings
title: Marketing Power For All
header-img: img/home-bg.jpg
email: dklongley@postpal.com
description: "Your website under your control"
baseurl: "https://dev.postpal.com"
url: "https://dev.postpal.com"
twitter_username: SBootstrap
github_username:  dindinet
facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
