title: Online Marketing Powers
header-img: img/home-bg.jpg
email: dklongley@postpal.com
description: Your website under your control
baseurl: 'https://dev.postpal.com'
url: 'https://dev.postpal.com'
twitter_username: postpal
github_username: dindinet
facebook_username: postpal
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
gems:
  #- jekyll-feed
exclude:
  - Gruntfile.js
  - less
  - node_modules
  - README.md
  - package.json
